# Generated by Django 3.2.18 on 2023-03-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='field1',
            new_name='Type',
        ),
    ]
