# Generated by Django 3.2.18 on 2023-04-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_csvdata_m2_declaration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='CIF_Value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='COMMODITY_DESC',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='GOODS_DESCRIPTION',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='Stat_Quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='Test',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='Test2',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='csvdata',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='M2_Declaration_Number',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
