# Generated by Django 3.2.18 on 2023-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20230410_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='Index',
            field=models.IntegerField(default=0),
        ),
    ]
